apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        log_format main '$http_x_forwarded_for - [$time_local] "$request" $status ' 
                        '"http_x_forwarded_proto: $http_x_forwarded_proto" '
                        '"http_cloudfront_forwarded_proto: $http_cloudfront_forwarded_proto" '
                        '"scheme: $scheme" '
                        '"Host: $host"';

        upstream webapp {
            server 127.0.0.1:4567;
        }

        server {
            listen 80;

            location / {
                set $force_ssl 1;
                if ($http_cloudfront_forwarded_proto = "https") {
                  set $force_ssl 0;
                }
                if ($http_x_forwarded_proto = "https") {
                  set $force_ssl 0;
                }
                if ($force_ssl) {
                  rewrite ^ https://$host$request_uri? permanent;
                }

                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_pass         http://webapp;
            }
        }
    }
